sudo: required
services:
  - docker

before_install:
  - docker build -t kindrat02/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kindrat02/react-test npm run test

after_success:
  - docker build -t kindrat02/multi-client ./client
  - docker build -t kindrat02/multi-server ./server
  - docker build -t kindrat02/multi-worker ./worker
  - docker build -t kindrat02/multi-nginx ./nginx
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push Docker images
  - docker push kindrat02/multi-client
  - docker push kindrat02/multi-server
  - docker push kindrat02/multi-worker
  - docker push kindrat02/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-440793530432'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY